# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 21:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import seekers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('dob', models.DateField(null=True)),
                ('nationality', models.CharField(max_length=10, null=True)),
                ('visa_type', models.CharField(max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True, unique=True)),
                ('phone_country_code', models.CharField(max_length=5, null=True)),
                ('near_station', django_mysql.models.JSONField(default=seekers.models.near_station)),
                ('education', models.CharField(max_length=20, null=True)),
                ('certificate', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, null=True, size=10)),
                ('japanese_lang_level', models.IntegerField(null=True)),
                ('jlpt_score', models.IntegerField(null=True)),
                ('lang_known', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, null=True, size=10)),
                ('job_interested', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, null=True, size=10)),
                ('job_experienced', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, null=True, size=10)),
                ('current_hourly_salary', models.IntegerField(null=True)),
                ('id_photo_path', models.FilePathField(null=True)),
                ('profile_pic_path', models.FilePathField(null=True)),
                ('residence_card_path', models.FilePathField(null=True)),
                ('intro_voice_path', models.FilePathField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_application', models.DateTimeField(null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('disp_lang', models.CharField(max_length=10, null=True)),
                ('seeker_status', models.CharField(max_length=10, null=True)),
                ('urgent', models.BooleanField(default=False)),
                ('fb_access_token', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
