# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.DateField(null=True)),
                ('seeker_status', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=10, unique=True)),
                ('station_home', models.CharField(max_length=20, null=True)),
                ('education', models.CharField(max_length=20, null=True)),
                ('certification', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, size=10)),
                ('japanese_lang_level', models.IntegerField(null=True)),
                ('jlpt_score', models.IntegerField(null=True)),
                ('language_know', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, size=10)),
                ('job_interested', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, null=True, size=10)),
                ('job_experienced', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, size=10)),
                ('current_salary', models.IntegerField(null=True)),
                ('urgent', models.BooleanField(default=False)),
                ('profile_pic_path', models.FilePathField(null=True)),
                ('residance_card_path', models.FilePathField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_applied_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('display_lang', models.CharField(max_length=10, null=True)),
                ('fb_access_token', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
