# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='id_photo_path',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='intro_voice_path',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='profile_pic_path',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='residence_card_path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
