# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('contact_number', models.CharField(max_length=10)),
                ('current_salary', models.IntegerField(null=True)),
                ('station_home', models.CharField(max_length=20)),
                ('station_school', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('skill', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, size=10)),
                ('certification', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, size=10)),
                ('japanese_lang_level', models.IntegerField(null=True)),
                ('jlpt_score', models.IntegerField(null=True)),
                ('language_know', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, size=10)),
                ('job_interested', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, size=10)),
                ('job_experienced', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, size=10)),
                ('user_img_files', django_mysql.models.JSONField(default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('display_lang', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
