# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_applied_status', models.CharField(max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job_profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_app.JobProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.DateField(null=True)),
                ('user_status', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=10, unique=True)),
                ('station_home', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('education', models.CharField(max_length=20, null=True)),
                ('japanese_lang_level', models.IntegerField(null=True)),
                ('job_interested', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, null=True, size=10)),
                ('urgent', models.BooleanField(default=False)),
                ('experience_level', models.BooleanField(default=False)),
                ('profile_pic_path', models.FilePathField(null=True)),
                ('identity_proof_path', models.FilePathField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_lang', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobapplied',
            name='user_profile_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserProfile'),
        ),
    ]
