# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
        ('user_app', '0002_auto_20170829_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job_profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_app.JobProfile')),
                ('user_profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserProfile')),
            ],
        ),
    ]
