# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='name',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
