# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:42
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models
import employers.models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='address',
            field=django_mysql.models.JSONField(default=employers.models.address_format),
        ),
    ]
