# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=20)),
                ('job_type', models.CharField(max_length=20)),
                ('job_status', models.CharField(max_length=10)),
                ('opening_count', models.IntegerField(null=True)),
                ('urgent', models.BooleanField(default=False)),
                ('work_time', django_mysql.models.JSONField(default=dict, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('address_coordinate', django_mysql.models.JSONField(default=dict, null=True)),
                ('station', models.CharField(max_length=20, null=True)),
                ('hour_wage_low', models.IntegerField(null=True)),
                ('hour_wage_high', models.IntegerField(null=True)),
                ('req_gender', models.CharField(max_length=6, null=True)),
                ('req_education', models.CharField(max_length=20, null=True)),
                ('req_japanese_lang_level', models.IntegerField(null=True)),
                ('req_experience_level', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='recruiter_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_app.RecruiterProfile'),
        ),
    ]
