# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprofile',
            name='address_coordinate',
        ),
        migrations.RemoveField(
            model_name='jobprofile',
            name='skill',
        ),
    ]
