# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seekers', '0001_initial'),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=20)),
                ('job_type', models.CharField(max_length=20)),
                ('job_description', models.CharField(blank=True, max_length=200)),
                ('job_status', models.CharField(default='active', max_length=10)),
                ('selling_point', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=110, size=10)),
                ('work_time', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('opening_count', models.IntegerField(blank=True)),
                ('urgent', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('rejected_lession', models.CharField(blank=True, max_length=100)),
                ('hour_wage_low', models.IntegerField(null=True)),
                ('hour_wage_high', models.IntegerField(null=True)),
                ('training_need', models.BooleanField(default=False)),
                ('training_day', models.IntegerField(null=True)),
                ('training_hour_wage_low', models.IntegerField(null=True)),
                ('training_hour_wage_high', models.IntegerField(null=True)),
                ('req_gender', models.CharField(blank=True, max_length=6)),
                ('req_education', models.CharField(blank=True, max_length=20)),
                ('req_japanese_lang_level', models.IntegerField(blank=True)),
                ('req_jlpt', models.IntegerField(null=True)),
                ('req_lang', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, null=True, size=10)),
                ('req_experience', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=55, null=True, size=5)),
                ('preferred_certificate', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, null=True, size=10)),
                ('work_brand_name', models.CharField(blank=True, max_length=15)),
                ('work_name', models.CharField(blank=True, max_length=15)),
                ('work_address', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('work_phone_number', models.CharField(blank=True, max_length=10)),
                ('work_fax_number', models.CharField(blank=True, max_length=10)),
                ('work_train', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('interview_name', models.CharField(blank=True, max_length=15)),
                ('interview_address', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('interview_phone_number', models.CharField(blank=True, max_length=10)),
                ('interview_fax_number', models.CharField(blank=True, max_length=10)),
                ('interview_train', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.Employer')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='application',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekers.Seeker'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set([('seeker', 'job')]),
        ),
    ]
