# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('seekers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekers.Seeker'),
        ),
    ]
